server:
  port: 8084

spring:
  application:
    name: bff
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/local-public.pem

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      consume:
        - w3c
        - b3
      produce:
        - w3c

logging:
  level:
    root: error
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level %magenta([${spring.application.name},%X{traceId:-},%X{spanId:-}]) %cyan(%logger{36}) - %msg%n"
