logging:
  level:
    root: info
    org.eventviewer: debug

leader-election:
  clustered: false

spring:
  kafka:
    security:
      protocol: PLAINTEXT
    admin:
      security:
        protocol: PLAINTEXT